services:
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL_SAME_HOST://:9095
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL_SAME_HOST://localhost:9095
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=L0ZEQh1yTbGhNNUE7-6wSQ
      - KAFKA_CFG_NODE_ID=1
    ports:
      - "9095:9095"
    volumes:
      - data-warehouse-kafka:/bitnami/kafka
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - kafka-network

  data-generator:
    build:
      context: .
      dockerfile: /docker/Dockerfile_generator
    environment:
      BROKERS_LIST: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  data-processor-car-incident:
    build:
      context: .
      dockerfile: /docker/Dockerfile_processor
    environment:
      BROKERS_LIST: kafka:9092
      INCIDENT_TYPE: CarIncident
    depends_on:
      - kafka
    networks:
      - kafka-network

  data-processor-flat-incident:
    build:
      context: .
      dockerfile: /docker/Dockerfile_processor
    environment:
      BROKERS_LIST: kafka:9092
      INCIDENT_TYPE: FlatIncident
    depends_on:
      - kafka
    networks:
      - kafka-network

  data-processor-health-incident:
    build:
      context: .
      dockerfile: /docker/Dockerfile_processor
    environment:
      BROKERS_LIST: kafka:9092
      INCIDENT_TYPE: HealthIncident
    depends_on:
      - kafka
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  data-warehouse-kafka:
