<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

    <ItemGroup>
	    <Protobuf Include="..\Protos\*.proto" GrpcServices="None" OutputDir="InsuranceIncidents" />
    </ItemGroup>
	<ItemGroup>
		<Compile Include="InsuranceIncidents\*.cs" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Include="QueryModels\User\User.cs" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.30.2" />
    <PackageReference Include="Grpc.Tools" Version="2.71.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="QueryModels\Insurance\" />
  </ItemGroup>

</Project>
