FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build

WORKDIR /app

COPY src/DataGenerator/DataGenerator.csproj ./DataGenerator/
COPY src/DTO/DTO.csproj ./DTO/
RUN dotnet restore ./DataGenerator/DataGenerator.csproj

COPY src/DataGenerator/ ./DataGenerator/
COPY src/DTO/ ./DTO/

RUN dotnet publish ./DataGenerator/DataGenerator.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "DataGenerator.dll"]