FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build

WORKDIR /app

COPY src/DataAPI/DataAPI.csproj ./DataAPI/
COPY src/DTO/DTO.csproj ./DTO/
RUN dotnet restore ./DataAPI/DataAPI.csproj

COPY src/DataAPI/ ./DataAPI/
COPY src/DTO/ ./DTO/

RUN dotnet publish ./DataAPI/DataAPI.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS runtime
WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "DataAPI.dll"]