// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HealthIncident.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DTO.InsuranceIncidents {

  /// <summary>Holder for reflection information generated from HealthIncident.proto</summary>
  public static partial class HealthIncidentReflection {

    #region Descriptor
    /// <summary>File descriptor for HealthIncident.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HealthIncidentReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRIZWFsdGhJbmNpZGVudC5wcm90bxIWRFRPLkluc3VyYW5jZUluY2lkZW50",
            "cxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90byKxAgoOSGVhbHRo",
            "SW5jaWRlbnQSEQoJRmlyc3ROYW1lGAEgASgJEhAKCExhc3ROYW1lGAIgASgJ",
            "EhIKClBhdHJvbnltaWMYAyABKAkSLQoJQmlydGhEYXRlGAQgASgLMhouZ29v",
            "Z2xlLnByb3RvYnVmLlRpbWVzdGFtcBJECgdBZGRyZXNzGAUgASgLMjMuRFRP",
            "Lkluc3VyYW5jZUluY2lkZW50cy5IZWFsdGhJbmNpZGVudC5IdW1hbkFkZHJl",
            "c3MSDAoEVGFncxgGIAMoCRpjCgxIdW1hbkFkZHJlc3MSEgoKUG9zdGFsQ29k",
            "ZRgBIAEoCRIPCgdDb3VudHJ5GAIgASgJEgwKBENpdHkYAyABKAkSDgoGU3Ry",
            "ZWV0GAQgASgJEhAKCEJ1aWxkaW5nGAUgASgJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DTO.InsuranceIncidents.HealthIncident), global::DTO.InsuranceIncidents.HealthIncident.Parser, new[]{ "FirstName", "LastName", "Patronymic", "BirthDate", "Address", "Tags" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::DTO.InsuranceIncidents.HealthIncident.Types.HumanAddress), global::DTO.InsuranceIncidents.HealthIncident.Types.HumanAddress.Parser, new[]{ "PostalCode", "Country", "City", "Street", "Building" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HealthIncident : pb::IMessage<HealthIncident>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HealthIncident> _parser = new pb::MessageParser<HealthIncident>(() => new HealthIncident());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HealthIncident> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DTO.InsuranceIncidents.HealthIncidentReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HealthIncident() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HealthIncident(HealthIncident other) : this() {
      firstName_ = other.firstName_;
      lastName_ = other.lastName_;
      patronymic_ = other.patronymic_;
      birthDate_ = other.birthDate_ != null ? other.birthDate_.Clone() : null;
      address_ = other.address_ != null ? other.address_.Clone() : null;
      tags_ = other.tags_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HealthIncident Clone() {
      return new HealthIncident(this);
    }

    /// <summary>Field number for the "FirstName" field.</summary>
    public const int FirstNameFieldNumber = 1;
    private string firstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FirstName {
      get { return firstName_; }
      set {
        firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "LastName" field.</summary>
    public const int LastNameFieldNumber = 2;
    private string lastName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LastName {
      get { return lastName_; }
      set {
        lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Patronymic" field.</summary>
    public const int PatronymicFieldNumber = 3;
    private string patronymic_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Patronymic {
      get { return patronymic_; }
      set {
        patronymic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "BirthDate" field.</summary>
    public const int BirthDateFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp birthDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp BirthDate {
      get { return birthDate_; }
      set {
        birthDate_ = value;
      }
    }

    /// <summary>Field number for the "Address" field.</summary>
    public const int AddressFieldNumber = 5;
    private global::DTO.InsuranceIncidents.HealthIncident.Types.HumanAddress address_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DTO.InsuranceIncidents.HealthIncident.Types.HumanAddress Address {
      get { return address_; }
      set {
        address_ = value;
      }
    }

    /// <summary>Field number for the "Tags" field.</summary>
    public const int TagsFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_tags_codec
        = pb::FieldCodec.ForString(50);
    private readonly pbc::RepeatedField<string> tags_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Tags {
      get { return tags_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HealthIncident);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HealthIncident other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FirstName != other.FirstName) return false;
      if (LastName != other.LastName) return false;
      if (Patronymic != other.Patronymic) return false;
      if (!object.Equals(BirthDate, other.BirthDate)) return false;
      if (!object.Equals(Address, other.Address)) return false;
      if(!tags_.Equals(other.tags_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
      if (LastName.Length != 0) hash ^= LastName.GetHashCode();
      if (Patronymic.Length != 0) hash ^= Patronymic.GetHashCode();
      if (birthDate_ != null) hash ^= BirthDate.GetHashCode();
      if (address_ != null) hash ^= Address.GetHashCode();
      hash ^= tags_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FirstName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LastName);
      }
      if (Patronymic.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Patronymic);
      }
      if (birthDate_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BirthDate);
      }
      if (address_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Address);
      }
      tags_.WriteTo(output, _repeated_tags_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FirstName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FirstName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LastName);
      }
      if (Patronymic.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Patronymic);
      }
      if (birthDate_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BirthDate);
      }
      if (address_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Address);
      }
      tags_.WriteTo(ref output, _repeated_tags_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FirstName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
      }
      if (LastName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
      }
      if (Patronymic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Patronymic);
      }
      if (birthDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BirthDate);
      }
      if (address_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Address);
      }
      size += tags_.CalculateSize(_repeated_tags_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HealthIncident other) {
      if (other == null) {
        return;
      }
      if (other.FirstName.Length != 0) {
        FirstName = other.FirstName;
      }
      if (other.LastName.Length != 0) {
        LastName = other.LastName;
      }
      if (other.Patronymic.Length != 0) {
        Patronymic = other.Patronymic;
      }
      if (other.birthDate_ != null) {
        if (birthDate_ == null) {
          BirthDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        BirthDate.MergeFrom(other.BirthDate);
      }
      if (other.address_ != null) {
        if (address_ == null) {
          Address = new global::DTO.InsuranceIncidents.HealthIncident.Types.HumanAddress();
        }
        Address.MergeFrom(other.Address);
      }
      tags_.Add(other.tags_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FirstName = input.ReadString();
            break;
          }
          case 18: {
            LastName = input.ReadString();
            break;
          }
          case 26: {
            Patronymic = input.ReadString();
            break;
          }
          case 34: {
            if (birthDate_ == null) {
              BirthDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(BirthDate);
            break;
          }
          case 42: {
            if (address_ == null) {
              Address = new global::DTO.InsuranceIncidents.HealthIncident.Types.HumanAddress();
            }
            input.ReadMessage(Address);
            break;
          }
          case 50: {
            tags_.AddEntriesFrom(input, _repeated_tags_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FirstName = input.ReadString();
            break;
          }
          case 18: {
            LastName = input.ReadString();
            break;
          }
          case 26: {
            Patronymic = input.ReadString();
            break;
          }
          case 34: {
            if (birthDate_ == null) {
              BirthDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(BirthDate);
            break;
          }
          case 42: {
            if (address_ == null) {
              Address = new global::DTO.InsuranceIncidents.HealthIncident.Types.HumanAddress();
            }
            input.ReadMessage(Address);
            break;
          }
          case 50: {
            tags_.AddEntriesFrom(ref input, _repeated_tags_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the HealthIncident message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class HumanAddress : pb::IMessage<HumanAddress>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<HumanAddress> _parser = new pb::MessageParser<HumanAddress>(() => new HumanAddress());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<HumanAddress> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::DTO.InsuranceIncidents.HealthIncident.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public HumanAddress() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public HumanAddress(HumanAddress other) : this() {
          postalCode_ = other.postalCode_;
          country_ = other.country_;
          city_ = other.city_;
          street_ = other.street_;
          building_ = other.building_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public HumanAddress Clone() {
          return new HumanAddress(this);
        }

        /// <summary>Field number for the "PostalCode" field.</summary>
        public const int PostalCodeFieldNumber = 1;
        private string postalCode_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string PostalCode {
          get { return postalCode_; }
          set {
            postalCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "Country" field.</summary>
        public const int CountryFieldNumber = 2;
        private string country_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Country {
          get { return country_; }
          set {
            country_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "City" field.</summary>
        public const int CityFieldNumber = 3;
        private string city_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string City {
          get { return city_; }
          set {
            city_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "Street" field.</summary>
        public const int StreetFieldNumber = 4;
        private string street_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Street {
          get { return street_; }
          set {
            street_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "Building" field.</summary>
        public const int BuildingFieldNumber = 5;
        private string building_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Building {
          get { return building_; }
          set {
            building_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as HumanAddress);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(HumanAddress other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (PostalCode != other.PostalCode) return false;
          if (Country != other.Country) return false;
          if (City != other.City) return false;
          if (Street != other.Street) return false;
          if (Building != other.Building) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (PostalCode.Length != 0) hash ^= PostalCode.GetHashCode();
          if (Country.Length != 0) hash ^= Country.GetHashCode();
          if (City.Length != 0) hash ^= City.GetHashCode();
          if (Street.Length != 0) hash ^= Street.GetHashCode();
          if (Building.Length != 0) hash ^= Building.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (PostalCode.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(PostalCode);
          }
          if (Country.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Country);
          }
          if (City.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(City);
          }
          if (Street.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(Street);
          }
          if (Building.Length != 0) {
            output.WriteRawTag(42);
            output.WriteString(Building);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (PostalCode.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(PostalCode);
          }
          if (Country.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Country);
          }
          if (City.Length != 0) {
            output.WriteRawTag(26);
            output.WriteString(City);
          }
          if (Street.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(Street);
          }
          if (Building.Length != 0) {
            output.WriteRawTag(42);
            output.WriteString(Building);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (PostalCode.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(PostalCode);
          }
          if (Country.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Country);
          }
          if (City.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(City);
          }
          if (Street.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Street);
          }
          if (Building.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Building);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(HumanAddress other) {
          if (other == null) {
            return;
          }
          if (other.PostalCode.Length != 0) {
            PostalCode = other.PostalCode;
          }
          if (other.Country.Length != 0) {
            Country = other.Country;
          }
          if (other.City.Length != 0) {
            City = other.City;
          }
          if (other.Street.Length != 0) {
            Street = other.Street;
          }
          if (other.Building.Length != 0) {
            Building = other.Building;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                PostalCode = input.ReadString();
                break;
              }
              case 18: {
                Country = input.ReadString();
                break;
              }
              case 26: {
                City = input.ReadString();
                break;
              }
              case 34: {
                Street = input.ReadString();
                break;
              }
              case 42: {
                Building = input.ReadString();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                PostalCode = input.ReadString();
                break;
              }
              case 18: {
                Country = input.ReadString();
                break;
              }
              case 26: {
                City = input.ReadString();
                break;
              }
              case 34: {
                Street = input.ReadString();
                break;
              }
              case 42: {
                Building = input.ReadString();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
